### ISSUE TITLE
Unclear how to use 

### ISSUE THREAD

**Issue by yarodevuci** [angusmillar/SmartHealthCard#8] opened 2021-10-02 02:29 UTC
Not clear how to use and how to generate keys

**Comment by yarodevuci** [comment] 2021-10-02 06:39
Generated Code is not scannable....

**Comment by angusmillar** [comment] 2021-10-07 02:38
Hi @yarodevuci, sorry to hear you are having difficulties. 
Your two comments above seem to indicate two separate issues and possibly the first you have resolved, give the second indicates you have created a QR Code, be it not working for you.  
I would point out that this library does not generate keys, that is not its purpose, although you will need keys to use it. On the repositories ReadMe page I did provide this link: [Creating Elliptical Curve Keys using OpenSSL](https://www.scottbrady91.com/OpenSSL/Creating-Elliptical-Curve-Keys-using-OpenSSL)  which I personally found very useful in generating keys. Also in the repository, there is this text file: [ReadMeOpenSSLCreateECCkeys.txt](https://github.com/angusmillar/SmartHealthCard/blob/master/ReadMeOpenSSLCreateECCkeys.txt) which are my own cheat notes taken from that site. I just follow these to generate keys when I require them. I would point out that these methods require the use of OpenSSL.exe and if you have Git installed you should find you already have OpenSSL.exe on your machine here: C:\Program Files\Git\usr\bin\openssl.exe, at least that was true for me.
On to your second issue, "Generated Code is not scannable....". I assume you mean you have generated a SMART Health Card QR Code with this library and are unable to successfully scan it, using something?
Perhaps this can help. 
If you use the site listed on the ReadMe page under the title 'Smart Health Card Development', this link: [Smart Health Card verifier site](https://demo-portals.smarthealth.cards/VerifierPortal.html) and then try and scan this QR Code below. This works for me yet I do admit it takes a bit of trying, ensure your camera is very parallel to the screen as you attempt. Perhaps enlarge the QR Code image as well, it might help. I can scan it with my PC web cam and with my phone, both work, but it does take some attempts. If you can't get this QR Code to scan then the issue is with your camera or technique of using it.  Once you can successfully scan that QR Code then move to the QR Code you generated and try again. I will also highlight that while the QR Code below will scan it will also error saying  '· keySet not valid. Expect {keys : JWK.Key[]} (Fatal)' which is because that QR Code's public key in not hosted on a public endpoint to allow the verification, but it does prove the scanning works.
I hope this help.
![QRCode-0](https://user-images.githubusercontent.com/13332180/136311547-0a77ed84-3805-470f-adb8-da52768a4449.png)

**Comment by angusmillar** [comment] 2021-10-26 12:38
Hi @yarodevuci, I'm going to close this issue but feel free to open it up again if you come back to it.

**Closed as completed by angusmillar** 2021-10-26 12:38 UTC
